language: php

sudo: false

dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-master.sh > xp-run
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth
  - echo "test.xar" > composer.pth
  - echo "hhvm.php7.all = 1" >> /etc/hhvm/php.ini

script:
  - (EXCD=0; for i in `ls -1 src/test/config/unittest/*.ini`; do echo "---> $i"; sh xp-run xp.unittest.Runner $i; RES=$?; if [ $RES -ne 0 ]; then EXCD=$RES; fi; done; exit $EXCD;)
